version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1.0

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy to was from template
          command: |
            set -x
            aws cloudformation deploy --template CloudFormation/CloudFormation1/resources.yml --stack-name PortfolioLambda-resources --capabilities CAPABILITY_NAMED_IAM

workflows:
  circleci-PortfolioLambda-workflow:
    jobs:
      - execute-cloudformation

